# Generated by Django 5.1.1 on 2024-09-24 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='LoginRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('phone_number', models.IntegerField(unique=True)),
                ('sms_verify', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='My_wallets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.CharField(max_length=250)),
                ('topUpBalance', models.CharField(max_length=250)),
                ('History', models.CharField(max_length=250)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_wallets', to='apps.loginregister')),
            ],
        ),
        migrations.CreateModel(
            name='MyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('numbOFRoom', models.CharField(max_length=250)),
                ('floor', models.CharField(max_length=250)),
                ('FloorBuilding', models.CharField(max_length=250)),
                ('remontBuilding', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('Facilities', models.CharField(max_length=250)),
                ('Photos', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_listing', to='apps.category')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_listing', to='apps.loginregister')),
            ],
        ),
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_profile', to='apps.loginregister')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=250)),
                ('Size', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('picture', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='apps.category')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter', models.CharField(max_length=250)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='apps.loginregister')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='apps.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.CharField(max_length=250)),
                ('picture', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('geo_location', models.CharField(max_length=250)),
                ('seller_number', models.CharField(max_length=20)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodcut_detail', to='apps.product')),
            ],
        ),
        migrations.CreateModel(
            name='Write_to_Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_number', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=250)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_to_author', to='apps.product_detail')),
            ],
        ),
    ]
